### ISSUE TITLE
Incorrect Content-Type on ActivityPub objects when they are retrieved by GET requests

### ISSUE THREAD

**Issue by grishka** [rekcuFniarB/messy-fediverse#1]
The Content-Type header is set to just `application/ld+json`:
![image](https://github.com/rekcuFniarB/messy-fediverse/assets/1478258/8dff916e-474e-4995-889c-8406b254ba6d)
According to [ActivityPub spec](https://www.w3.org/TR/activitypub/#server-to-server-interactions), it should be either `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` (the profile part is important) or `application/activity+json`.

**Comment by rekcuFniarB** [comment]
Fixed, thanks.
